name: Sync frontend-nextjs to public repo

on:
  push:
    branches:
      - main
    paths:
      - "frontend-nextjs/**"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git config
        run: |
          git config user.name "judahwon"
          git config user.email "hwondaa@gmail.com"

      - name: Split subtree
        run: |
          git subtree split --prefix=frontend-nextjs -b frontend-split

      - name: Debug token
        run: |
          echo "token length: ${#TOKEN}"
        env:
          TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}

      - name: Push to public repo
        env:
          TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          git push https://judahwon:${TOKEN}@github.com/ChodaeDev/frontend-public.git frontend-split:main --force